# Generated by Django 2.2.1 on 2019-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('project_url', models.URLField()),
                ('project_decription', models.TextField()),
                ('project_title_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
