# Generated by Django 2.2.1 on 2019-06-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_title_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
