# Generated by Django 2.2.1 on 2019-06-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190621_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_decription',
            new_name='project_description',
        ),
    ]
